# Generated by Django 4.0 on 2021-12-23 14:20

from django.db import migrations, models
import django.db.models.deletion
import restaurantFood.models.food


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0002_foodtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('quantity', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_date')),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_column='updated_date')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('foodPicture', models.ImageField(upload_to=restaurantFood.models.food.RestaurantFood.restaurant_directory_path)),
                ('origin', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_date')),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_column='updated_date')),
                ('foodCategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food.foodcategory')),
                ('foodType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food.foodtype')),
                ('ingredients', models.ManyToManyField(default=None, to='restaurantFood.Ingredient')),
            ],
        ),
    ]
