# Generated by Django 4.0 on 2021-12-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantFood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
