# Generated by Django 4.0 on 2021-12-23 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_restaurant_foodtype_alter_restaurant_module'),
        ('restaurantFood', '0002_alter_ingredient_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantfood',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.user'),
        ),
    ]
