# Generated by Django 4.0 on 2022-02-01 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_delivery_alter_user_restaurant_user_delivery'),
        ('restaurantFood', '0003_restaurantfood_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.user'),
        ),
    ]
