# Generated by Django 4.0 on 2022-02-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantFood', '0004_ingredient_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantfood',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
