# Generated by Django 4.0 on 2022-07-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantFood', '0005_alter_ingredient_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantfood',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
