# Generated by Django 4.0 on 2022-08-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantFood', '0006_alter_restaurantfood_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantfood',
            name='origin',
        ),
        migrations.AddField(
            model_name='restaurantfood',
            name='cooking_time',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='restaurantfood',
            name='nutritional_value',
            field=models.TextField(default=None, null=True),
        ),
    ]
