# Generated by Django 4.0 on 2022-08-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantFood', '0007_remove_restaurantfood_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_date'),
        ),
        migrations.AlterField(
            model_name='restaurantfood',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_date'),
        ),
    ]
