# Generated by Django 4.0 on 2022-08-12 22:26

from django.db import migrations, models
import django.db.models.deletion
import restaurantFood.models.food


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_user_picture'),
        ('food', '0004_foodimage_foodpicture'),
        ('restaurantFood', '0008_alter_ingredient_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantfood',
            name='activated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activate_food', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='restaurantfood',
            name='activated_reason',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='restaurantfood',
            name='foodPicture_related',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.foodimage'),
        ),
        migrations.AlterField(
            model_name='restaurantfood',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='restaurantfood',
            name='foodPicture',
            field=models.ImageField(default=None, null=True, upload_to=restaurantFood.models.food.RestaurantFood.restaurant_directory_path),
        ),
    ]
