# Generated by Django 4.0 on 2022-02-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0002_rename_category_drinkcategory_rename_type_drinktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drinktype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
