# Generated by Django 4.0 on 2022-10-08 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0004_drink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='drinkPicture',
        ),
    ]
