# Generated by Django 4.0 on 2022-10-08 18:22

from django.db import migrations, models
import drink.models.drink


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0005_remove_drink_drinkpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='drinkPicture',
            field=models.ImageField(default=None, null=True, upload_to=drink.models.drink.Drink.drinks_directory_path),
        ),
    ]
