# Generated by Django 4.0 on 2021-12-23 13:10

from django.db import migrations, models
import django.db.models.deletion
import restaurantDrink.models.drink


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drink', '0002_rename_category_drinkcategory_rename_type_drinktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('drinkPicture', models.ImageField(upload_to=restaurantDrink.models.drink.RestaurantDrink.restaurant_directory_path)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_date')),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_column='updated_date')),
                ('drinkCategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drink.drinkcategory')),
                ('drinkType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drink.drinktype')),
            ],
        ),
    ]
