# Generated by Django 4.0 on 2022-02-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantDrink', '0003_alter_restaurantdrink_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdrink',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
