# Generated by Django 4.0 on 2022-07-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantDrink', '0004_restaurantdrink_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantdrink',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
