# Generated by Django 4.0 on 2022-08-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantDrink', '0005_alter_restaurantdrink_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantdrink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_date'),
        ),
    ]
