# Generated by Django 4.0 on 2022-10-22 06:40

from django.db import migrations, models
import django.db.models.deletion
import restaurantDrink.models.drink


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0006_drink_drinkpicture'),
        ('restaurantDrink', '0007_restaurantdrink_admin_drink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantdrink',
            name='drinkCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='drink.drinkcategory'),
        ),
        migrations.AlterField(
            model_name='restaurantdrink',
            name='drinkPicture',
            field=models.ImageField(null=True, upload_to=restaurantDrink.models.drink.RestaurantDrink.restaurant_directory_path),
        ),
        migrations.AlterField(
            model_name='restaurantdrink',
            name='drinkType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='drink.drinktype'),
        ),
    ]
