# Generated by Django 4.0 on 2021-12-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='module',
            field=models.ManyToManyField(blank=True, default=None, to='accounts.Module'),
        ),
    ]
