# Generated by Django 4.0 on 2022-01-12 17:14

import accounts.models.delivery
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_restaurant_foodtype_alter_restaurant_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateTimeField()),
                ('scan_cni', models.ImageField(blank=True, null=True, upload_to=accounts.models.delivery.Delivery.delivery_directory_path)),
                ('address', models.CharField(max_length=128)),
                ('licence', models.CharField(max_length=128)),
                ('brand', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('power', models.CharField(max_length=128)),
                ('year', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.restaurant'),
        ),
        migrations.AddField(
            model_name='user',
            name='delivery',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.delivery'),
        ),
    ]
