# Generated by Django 4.0 on 2022-03-28 14:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_module_description_alter_role_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), default=None, null=True, size=2),
        ),
    ]
