# Generated by Django 4.0 on 2022-04-01 14:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_delivery_licence_remove_delivery_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='location',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), default=None, null=True, size=2),
        ),
    ]
