# Generated by Django 4.0 on 2022-07-30 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_restaurant_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='activate_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activate_by', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='activate_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
