# Generated by Django 4.0 on 2022-08-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_delivery_activate_by_delivery_activate_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_date'),
        ),
    ]
