# Generated by Django 4.0 on 2022-08-04 20:27

import accounts.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_restaurant_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(default=None, null=True, upload_to=accounts.models.user.User.user_directory_path),
        ),
    ]
