# Generated by Django 4.0 on 2022-08-22 07:35

import accounts.models.restaurant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_profileimage_remove_restaurant_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='picture',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='picture',
            field=models.ImageField(default=None, null=True, upload_to=accounts.models.restaurant.Restaurant.restaurant_directory_path),
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='profile_picture',
            field=models.ImageField(default=None, null=True, upload_to=accounts.models.restaurant.Restaurant.restaurant_directory_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
