# Generated by Django 4.0 on 2022-10-18 20:29

import accounts.models.restaurant
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_restaurant_picture_restaurant_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='rccm',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='closing_hour',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='immatriculation',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='internet_site',
            field=models.URLField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_hour',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='picture_xx',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(default=None, null=True, upload_to=accounts.models.restaurant.Restaurant.restaurant_directory_path), default=None, null=True, size=None),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_channel',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='social_network_link',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=None, null=True, size=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
    ]
