# Generated by Django 4.0 on 2022-10-18 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_remove_restaurant_picture_xx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='profile_picture',
        ),
    ]
