# Generated by Django 4.0 on 2022-10-18 20:55

import accounts.models.restaurant
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_remove_restaurant_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='picture',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(default=None, null=True, upload_to=accounts.models.restaurant.Restaurant.restaurant_directory_path), default=None, null=True, size=None),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='profile_picture',
            field=models.ImageField(default=None, null=True, upload_to=accounts.models.restaurant.Restaurant.restaurant_directory_path),
        ),
    ]
