# Generated by Django 4.0 on 2022-10-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_rename_picture_xx_restaurant_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='picture',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='picture_restaurant',
            field=models.ManyToManyField(to='accounts.Picture'),
        ),
    ]
