# Generated by Django 4.0 on 2022-02-12 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_module_description_alter_role_description'),
        ('restaurantCommande', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='cancel_validation_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancel_validation_user', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='commande',
            name='validated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_user', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_user', to='accounts.user'),
        ),
    ]
