# Generated by Django 4.0 on 2022-04-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantCommande', '0003_rename_is_valid_commande_is_restaurant_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='is_delivery_check',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='commande',
            name='is_delivery_valid',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='commande',
            name='is_restaurant_valid',
            field=models.BooleanField(),
        ),
    ]
