# Generated by Django 4.0 on 2022-06-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantCommande', '0005_alter_commande_is_delivery_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='cooking_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='site_delivery',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
