# Generated by Django 4.0 on 2022-06-29 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantMenu', '0008_alter_menu_description_and_more'),
        ('restaurantCommande', '0006_commande_cooking_time_commande_site_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='commande',
            name='menu',
        ),
        migrations.AddField(
            model_name='commande',
            name='menuQ',
            field=models.ManyToManyField(through='restaurantCommande.MenuQuantity', to='restaurantMenu.Menu'),
        ),
        migrations.AddField(
            model_name='menuquantity',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantCommande.commande'),
        ),
        migrations.AddField(
            model_name='menuquantity',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantMenu.menu'),
        ),
    ]
