# Generated by Django 4.0 on 2022-06-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantCommande', '0007_menuquantity_remove_commande_menu_commande_menuq_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='menuQ',
            new_name='menu',
        ),
    ]
