# Generated by Django 4.0 on 2022-06-29 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantFood', '0005_alter_ingredient_description_and_more'),
        ('restaurantDrink', '0004_restaurantdrink_price'),
        ('restaurantCommande', '0008_rename_menuq_commande_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FoodQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='commande',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='food',
        ),
        migrations.AddField(
            model_name='commande',
            name='drinkQ',
            field=models.ManyToManyField(through='restaurantCommande.DrinkQuantity', to='restaurantDrink.RestaurantDrink'),
        ),
        migrations.AddField(
            model_name='commande',
            name='foodQ',
            field=models.ManyToManyField(through='restaurantCommande.FoodQuantity', to='restaurantFood.RestaurantFood'),
        ),
        migrations.AddField(
            model_name='foodquantity',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantCommande.commande'),
        ),
        migrations.AddField(
            model_name='foodquantity',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantFood.restaurantfood'),
        ),
        migrations.AddField(
            model_name='drinkquantity',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantCommande.commande'),
        ),
        migrations.AddField(
            model_name='drinkquantity',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantDrink.restaurantdrink'),
        ),
    ]
