# Generated by Django 4.0 on 2022-06-29 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantCommande', '0009_drinkquantity_foodquantity_remove_commande_drink_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='drinkQ',
            new_name='drink',
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='foodQ',
            new_name='food',
        ),
    ]
