# Generated by Django 4.0 on 2022-06-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantCommande', '0010_rename_drinkq_commande_drink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='drinkquantity',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='foodquantity',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='menuquantity',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
