# Generated by Django 4.0 on 2022-07-14 17:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_delivery_date_of_birth'),
        ('restaurantCommande', '0011_alter_commande_total_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('note_livreur', models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('note_restaurant', models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_date')),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_column='updated_date')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurantCommande.commande')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.user')),
            ],
        ),
    ]
