# Generated by Django 4.0 on 2022-07-19 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantCommande', '0012_noteservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='name',
        ),
    ]
