# Generated by Django 4.0 on 2022-07-21 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantCommande', '0013_remove_commande_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='description',
        ),
    ]
