# Generated by Django 4.0 on 2022-08-04 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantFood', '0007_remove_restaurantfood_origin_and_more'),
        ('restaurantCommande', '0014_remove_commande_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='message',
        ),
        migrations.CreateModel(
            name='NoteFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default=None, null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantFood.restaurantfood')),
            ],
        ),
        migrations.CreateModel(
            name='NoteComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default=None, null=True)),
                ('foods', models.ManyToManyField(to='restaurantCommande.NoteFood')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='comments',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantCommande.notecomments'),
        ),
    ]
