# Generated by Django 4.0 on 2022-08-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantCommande', '0015_remove_note_message_notefood_notecomments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_date'),
        ),
        migrations.AlterField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_date'),
        ),
        migrations.AlterField(
            model_name='noteservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_date'),
        ),
    ]
