# Generated by Django 4.0 on 2022-08-10 21:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantDrink', '0006_alter_restaurantdrink_updated_at'),
        ('accounts', '0023_user_picture'),
        ('restaurantFood', '0008_alter_ingredient_updated_at_and_more'),
        ('restaurantCommande', '0017_notedrink_notecomments_drinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='noteservice',
            name='note_livreur',
        ),
        migrations.AlterField(
            model_name='note',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantCommande.commande'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='noteservice',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantCommande.commande'),
        ),
        migrations.AlterField(
            model_name='noteservice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
        migrations.CreateModel(
            name='NoteRestaurantFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, default=None, null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantFood.restaurantfood')),
            ],
        ),
        migrations.CreateModel(
            name='NoteRestaurantDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, default=None, null=True)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantDrink.restaurantdrink')),
            ],
        ),
        migrations.CreateModel(
            name='NoteRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, default=None, null=True)),
                ('drinks', models.ManyToManyField(to='restaurantCommande.NoteRestaurantDrink')),
                ('foods', models.ManyToManyField(to='restaurantCommande.NoteRestaurantFood')),
            ],
        ),
        migrations.AddField(
            model_name='noteservice',
            name='note_delivery',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantCommande.notedelivery'),
        ),
        migrations.AlterField(
            model_name='noteservice',
            name='note_restaurant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantCommande.noterestaurant'),
        ),
    ]
