"""
Django settings for wazieats project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': 'restaurants',
        'USER': 'postgres',
        'PASSWORD': 'incentplus',
        'HOST': 'localhost',
        'PORT': '',            # Set to empty string for default.
    }
}

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
# EMAIL_HOST_USER = 'wazieats@gmail.com'
# EMAIL_HOST_PASSWORD = 'WaziEats12@'
# EMAIL_HOST_USER = 'admin@wazieats.com'
# EMAIL_HOST_PASSWORD = 'WIvanka88'
EMAIL_HOST_USER = 'tech@wazieats.com'
EMAIL_HOST_PASSWORD = 'TechWaziE@ts2022'
EMAIL_USE_TLS = True

APP = {
    'site_name': 'WaziEats',
    'site_url': 'https://wazieats.com/',
    'admin_url': 'https://admin.wazieats.com/',
    'email': {
        'from': 'admin@wazieats.com'
    }
}

ADMINS = [
    ("WaziEats Food Delivery", "admin@wazieats.com")
]

RADIUS_NOTIF_DELIVERY = 500   # En metres, rayon des livreurs à notifier
RADIUS_NOTIF_CLIENT = 100   # En metres, rayon des livreurs à notifier

MAX_TIME = {
    'delete_commande': 5,   # temps en minutes, maximum pour annuler une commande
    'update_commande': 5,   # temps en minutes, maximum pour modifier une commande
    'cancel_valid_commande': 5,     # temps en minutes, maximum pour annuler une validation d'une commande
    'notif_client_rejet_commande': 10     # temps en minutes, maximum pour notifier le client qu'une commande ne sera pas traité
}
