# Generated by Django 4.0 on 2022-02-01 11:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurantFood', '0003_restaurantfood_created_by'),
        ('accounts', '0012_delivery_alter_user_restaurant_user_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('menu_day', models.PositiveIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('repeat', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_date')),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_column='updated_date')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('calculated_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('real_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status_price', models.IntegerField(choices=[(1, 'Percent'), (2, 'Real')])),
                ('percent', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_date')),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_column='updated_date')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.user')),
                ('foods', models.ManyToManyField(to='restaurantFood.RestaurantFood')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='restaurantMenu.publicationperiod')),
            ],
        ),
    ]
