# Generated by Django 4.0 on 2022-02-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantMenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationperiod',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicationperiod',
            name='start_date',
            field=models.DateField(),
        ),
    ]
