# Generated by Django 4.0 on 2022-02-01 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantMenu', '0002_alter_publicationperiod_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='percent',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='real_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True),
        ),
    ]
