# Generated by Django 4.0 on 2022-02-01 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantMenu', '0003_alter_menu_percent_alter_menu_real_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='percent',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(-100.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
