# Generated by Django 4.0 on 2022-02-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantMenu', '0005_alter_menu_calculated_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='calculated_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True),
        ),
    ]
