# Generated by Django 4.0 on 2022-02-01 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_delivery_alter_user_restaurant_user_delivery'),
        ('restaurantMenu', '0006_alter_menu_calculated_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_date')),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_column='updated_date')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.user')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurantMenu.menu')),
            ],
        ),
    ]
