# Generated by Django 4.0 on 2022-07-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantMenu', '0008_alter_menu_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='calculated_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='real_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
