# Generated by Django 4.0 on 2022-08-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantDrink', '0005_alter_restaurantdrink_price'),
        ('restaurantMenu', '0009_alter_menu_calculated_price_alter_menu_real_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='drinks',
            field=models.ManyToManyField(to='restaurantDrink.RestaurantDrink'),
        ),
    ]
