from .schema_delivery import *
from .schema_menu import *
from .schema_commande import *
from .schema_notes import *
from .schema_restaurant_drink import *
from .schema_restaurant_food import *
from .schema_client import *
from .schema_comment import *
from .schema_user import *
from .schema_restaurant import *
from .schema_role import *
from .schema_login import *
