# Generated by Django 4.0 on 2022-02-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_foodtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
