# Generated by Django 4.0 on 2022-08-12 19:44

from django.db import migrations, models
import django.db.models.deletion
import food.models.food_picture


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_user_picture'),
        ('food', '0003_alter_foodcategory_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=food.models.food_picture.FoodImage.foods_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='FoodPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_date')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_date')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.user')),
                ('images', models.ManyToManyField(to='food.FoodImage')),
            ],
        ),
    ]
